site_name: MkDocs Material Template with GitHub-Flavored Markdown
site_url: 'https://kiyoon.github.io/mkdocs-material-template/'
repo_url: 'https://github.com/kiyoon/mkdocs-material-template'
copyright: |
  &copy; 2025 <a href="https://kiyoon.kim"  target="_blank" rel="noopener">Kiyoon Kim</a>
watch: [mkdocs.yml, README.md, src/]
validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn

nav:
  - Home:
      - Overview: index.md
      - Changelog: CHANGELOG.md
  - MkDocs:
      - Setting Up GitLab Pages: mkdocs/gitlab_pages.md
      - Referencing Python Code: mkdocs/mkdocstrings.md
  # defer to gen-files + literate-nav
  - API reference:
      - mkdocstrings-python: reference/

theme:
  name: material
  font:
    text: Noto Sans Korean
    code: Jetbrains Mono
  features:
    - toc.follow
    - navigation.top
    - navigation.footer
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.path
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: ko
  palette:
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: teal
      accent: purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: black
      accent: lime
      toggle:
        icon: material/weather-night
        name: Switch to system preference

plugins:
  - search
  - callouts:
      aliases: false
  - gen-files:
      scripts:
        - scripts/gen_ref_nav.py
  - literate-nav:
      nav_file: SUMMARY.md
  - mkdocstrings:
      handlers:
        python:
          options:
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            members_order: source
            allow_inspection: false # for .pyi stubs to work
          paths: [src] # search packages in the src folder

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/deargen/python-project-template-2024
  version:
    provider: mike

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tilde # strikethrough with ~~ ~~
  - toc:
      permalink: true
  # MathJax
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra_admonitions.css
  - stylesheets/mkdocstrings.css
