name: Deploy MkDocs on latest commit

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy-mkdocs:
    uses: deargen/workflows/.github/workflows/deploy-mkdocs.yml@master
    with:
      deploy-type: latest
      requirements-file: requirements.txt
    #   gitlab-project: ${{ vars.GITLAB_PROJECT }}
    #   gitlab-branch: master
    # secrets:
    #   GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
